content/src/service/ServiceImpl.ts
content/src/service/history/HistoryManager.ts
content/src/service/history/HistoryManagerImpl.ts
content/test/integration/E2EAssertions.ts
content/test/unit/service/history/MockedHistoryManager.ts

We are now checking if we need to read and parse the immutable history before actually doing so. Previously, we would always read it.

Reading immutable history only if necessary

---

content/src/service/synchronization/ContentCluster.ts
content/src/service/synchronization/SynchronizationManager.ts
content/src/service/synchronization/clients/contentserver/ActiveContentServerClient.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/syncronization/name-change-handling.spec.ts

This PR adds to content servers the ability to support name changes on other servers. It does so by changing two things:
1. When syncing with the DAO (every 5 min by default), if we detect a new name, we update it
2. When syncing with other servers, if there is no new deployment, we won't update it's estimated immutable time if the name is different from the expected one.

Now the content server can support name changes without problems

---

content/src/Environment.ts
content/src/service/ServiceFactory.ts
content/src/service/ServiceImpl.ts
content/src/service/synchronization/ClusterSynchronizationManagerFactory.ts
content/src/service/synchronization/ContentCluster.ts
content/src/service/synchronization/ContentClusterFactory.ts
content/src/service/synchronization/SynchronizationManager.ts
content/src/service/synchronization/clients/contentserver/ActiveContentServerClient.ts
content/src/service/validations/Validations.ts
content/src/service/validations/ValidationsFactory.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/TestServer.ts
content/test/integration/syncronization/cluster-synchronization.spec.ts
content/test/integration/syncronization/error-handling.spec.ts
content/test/integration/syncronization/name-change-handling.spec.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts
content/test/unit/service/validations/Validator.spec.ts

Changes:
A. We made TTL backwards time configurable, but not by env variable. We did this so that we can modify it in tests
B. We added a few tests:
1. `When a server finds a new deployment with already known content, it can still deploy it successfully`
2. `When a user tries to fix an entity, it doesn't matter if there is already a newer entity deployed`
3. `When a pointer is denylisted, then the history is empty`
4. `When a pointer is not denylisted, then it reports the history correctly`

Add many content server tests

---

comms/peer/src/Peer.ts
version.bzl

Making sure to use known peer data when updating network and choosing candidates to disconnect from.
In the existing codebase, the chosen peer might not be properly initialized (with known peer data), thus resulting in a null reference and an exception afterwards when trying to sort them out.

fix: use known peers to ensure data availability when updating network

---

commons/servers/DAOClient.ts
content/src/service/synchronization/ContentCluster.ts
contracts/utils.ts

Stop using WebSockets to connect to infura, and use HTTP instead.
I manually verified that when the connections goes down, and then goes up again, the server can still sync correctly

Replace WebSockets with HTTP to connect to infura

---

content/src/helpers/FetchHelper.ts
content/src/service/validations/Validations.ts
content/test/unit/service/validations/Validator.spec.ts

We are making 3 small fixes in the same PR:
1. When we retry an action and fail, we were incorrectly logging that 0 attempts were made
2. We are allowing the "future" deployments 15 min into the future (it was 5 min previously)
3. We didn't allow legacy entities to be deployed if there was an entity with a newer version deployed. The problem is, that during sync, we should still allow these deployments. We fixed it

Fix: allow legacy deployments in the past

---

content/src/Server.ts
content/src/controller/Controller.ts
content/src/controller/ControllerDeploymentFactory.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/deployments/DeploymentManager.ts
content/src/service/deployments/client/DeploymentsClient.ts
content/src/service/history/HistoryManagerImpl.ts
content/src/storage/repositories/DeploymentsRepository.ts
content/src/storage/repositories/MigrationDataRepository.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/helpers/service/synchronization/MockedContentCluster.ts
content/test/integration/E2EAssertions.ts
content/test/integration/TestServer.ts
content/test/integration/service/deployments/client/DeploymentsClient.spec.ts
content/test/integration/syncronization/cluster-synchronization.spec.ts
content/test/integration/syncronization/denylist-handling.spec.ts
content/test/integration/syncronization/error-handling.spec.ts
content/test/integration/syncronization/node-onboarding.spec.ts
content/test/integration/syncronization/unreachable-node.spec.ts
content/test/integration/upload-and-download.spec.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts

We are adding a `/deployments` endpoint that exposes all deployments. Right now, they can only be filtered by: `fromLocalTimestamp` & `toLocalTimestamp`. Results are paginated similarly to the `/history` endpoint.
In the near future, we will add more filters to the endpoint and try to replace the `/entities` and `/audit` endpoints

feat: adding deployments endpoint

---

content/src/denylist/Denylist.ts
content/src/denylist/DenylistServiceDecorator.ts

As of #121, we have a signature validation function available on the `commons` module. This function is safer than the one being used today, so we want to start using it.

refactor: use common signature validation

---

content/src/controller/Controller.ts
content/src/migrations/scripts/1591278192053_add_indexes.ts
content/src/service/deployments/DeploymentManager.ts
content/src/service/deployments/client/DeploymentsClient.ts
content/src/service/history/HistoryManagerImpl.ts
content/src/storage/repositories/DeploymentsRepository.ts
content/test/integration/E2EAssertions.ts
content/test/integration/E2ETestEnvironment.ts
content/test/integration/TestServer.ts
content/test/integration/service/deployments/client/DeploymentsClient.spec.ts
content/test/integration/service/deployments/deltas-check.spec.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/integration/service/order-check.spec.ts
content/test/integration/service/same-timestamp-check.spec.ts

We are adding a few filters to the `/deployments` endpoint. Previously, we only had:
* fromLocalTimestamp
* toLocalTimestamp
Now, we are adding:
* deployedBy
* entityTypes
* entityIds
* pointers
* onlyCurrentlyPointed
Also, now, by default we won't show the `auditInfo` unless a query param called `showAudit` is set to true. In the near future, we will replace this query param with a `fields` parameter, where you can specify the fields you would like to retrieve.

feat: add filters to deployments endpoint

---

comms/lighthouse/src/peersService.ts
comms/lighthouse/src/server.ts

Added a check to ensure that a peer cannot connect more than once to the same lighthouse

fix: Disallow same address in lighthouse

---

comms/lighthouse/src/naming.ts

The lighthouse now checks the name even if the response of other lighthouses was not 200 (for instance, 503 when not ready)

fix: Checking name even if response not ok

---

content/src/service/ServiceImpl.ts
content/src/service/validations/ValidationContext.ts
content/src/service/validations/Validations.ts
content/test/integration/syncronization/error-handling.spec.ts
content/test/unit/service/deployments/NoOpDeploymentManager.ts

**Problem**:
As of now, all entities that are re-deployed fail. The problem with this is that during sync, there could be a race condition that causes these failures. Even though the chances after #139 should be really really small, we need to prevent these types of errors and give ourselves the opportunity to fix these deployments that are already marked as failed.
**Solution**
We are basically doing one small change with the following impact:
1. We are no longer failing when entities are re-deployed during sync of fix deployments. In those cases, we will just not deploy it. However, during local/direct deployments, we will continue to fail.
2. Since fix deployments allow re-deploys, if we trigger one with a failed deployment (even if it was a re-deployment error), it will be fixed and …

Allow fixing re-deployment errors

---

content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/synchronization/ClusterUtils.ts
content/src/service/synchronization/ContentCluster.ts
content/src/service/synchronization/EventStreamProcessor.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts

Ok, so we are doing a few minor changes on this PR.
1. We are adding pointer denylist filtering to the `/deployments` endpoint. This was long overdue. The logic will remain consistent with the `/entities` endpoint. Applied to the `/deployments` endpoint, this means that: deployments will not be returned if all pointers in the intersection between the 'pointers' filter and the deployment's pointers are denylisted. If the 'pointers' filter is not used, then we won't filter anything out.
2. When array query params are used (and not set), then they will remain `undefined` by default. Before, they were set as an empty array. This caused some weird scenarios on the `/deployments` endpoint, since filters were marked as set, when they weren't
3. When executing a shuffle on the content server …

feat: many minor changes

---

content/src/service/access/AccessCheckerImpl.ts
content/src/service/access/AccessCheckerImplFactory.ts
content/test/integration/service/access/AccessCheckerImpl.spec.ts
content/test/manual/check-failed-deployments.spec.ts
content/test/unit/service/access/AccessCheckerImpl.spec.ts
content/test/unit/service/validations/Validations.spec.ts
package.json
yarn.lock

We are now calling the `Fetcher` on `dcl-catalyst-commons` when querying `thegraph`. This fetcher already uses a timeout for requests

fix: add timeout when querying thegraph

---

package.json
yarn.lock

We are updating the library https://www.npmjs.com/package/dcl-crypto to the newest version

chore: update dcl crypto

---

content/src/Environment.ts
content/src/Server.ts
content/src/controller/Controller.ts
content/src/controller/ControllerFactory.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/garbage-collection/GarbageCollectionManager.ts
content/src/service/snapshots/SnapshotManager.ts
content/src/service/snapshots/SnapshotManagerFactory.ts
content/src/service/system-properties/SystemProperties.ts
content/src/storage/repositories/DeploymentsRepository.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/helpers/service/snapshots/NoOpGarbageCollectionManager.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/Server.spec.ts
content/test/integration/service/snapshots/SnapshotManager.spec.ts

We are now adding snapshots. These can be defined as a list of all the active entities on the content server, at a given time. By active, we mean entities that are currently referenced by at least one pointer.
Every N deployments (N depends on the entity type) we will create a snapshot, and add it to the storage. Snapshots will be a text file with a JSON array with the following type: `[EntityId, Pointer[]][]`. The good part about this, is that you could easy read this file into an ES6 Map like this:
```
const fileContent: Buffer = fs.readFile(...)
const array: [EntityId, Pointer[]][] = JSON.parse(fileContent.toString())
const asMap: Map<EntityId, Pointer[]> = new Map(array)
```
Then, we will expose a `/snapshot` endpoint that displays the hash of the latest snapshot, and the local …

feat: adding content server snapshots

---

.dockerignore
Dockerfile
entrypoint.sh
prepare_for_docker_image.sh

Now docker image is built inside docker context, so it can be built on any OS that supports docker

chore: Enable docker image to be built on other OS than linux

---

commons/servers/DAOClient.ts
commons/servers/test/DAOContractClient.spec.ts
comms/lighthouse/src/server.ts
content/src/Environment.ts
content/src/service/synchronization/clients/DAOClientFactory.ts
content/src/service/synchronization/clients/HardcodedDAOClient.ts
content/test/helpers/service/synchronization/clients/MockedDAOClient.ts

We are now adding a new ENV var to select the nodes you want to connect to, instead of reading the DAO's contract

feat: add possibility to hardcode DAO

---

content/src/service/ServiceImpl.ts
content/test/integration/service/concurrent-deployments.spec.ts

We are now preventing concurrent deployments on the same pointers. These are EXTREMELY rare, but in the event they happen, the database could end up inconsistent.

fix: prevent concurrent deployments on the same pointers

---

comms/peer/src/Peer.ts
comms/peer/test/Peer.integration.spec.ts
version.bzl

Encodes peer id as URI when doing an HTTP request to leave a room to avoid issues with potential special characters in the id alphabet (e.g. %) that were causing errors in the client.

fix: encode peer id when leaving room

---

content/src/service/ServiceImpl.ts
content/src/storage/FileSystemContentStorage.ts
content/test/integration/service/concurrent-deployments.spec.ts

We are making the content server more reliable, as we are handling unexpected errors when:
* Moving a file
* A deployment fails

fix: clear pointer blocker with errors

---

.gitignore
comms/peer/src/Peer.ts
comms/peer/src/PeerWebRTCHandler.ts
comms/peer/src/types.ts
npm-link-peer.sh

To be able to develop Peer library with Explorer more easily, added a script to create an NPM link.
Also added the low-level packet to packet callback. This can be useful if there is some information that the user of the peer library needs to use in the callback (for instance, the sequence id).

chore: NPM link support for peer library & added packet to packet callback

---

content/src/controller/Controller.ts

By spec, etag must be a double quoted string. Otherwise it is ignored

fix: edge cache issue

---

content/src/service/ServiceImpl.ts
content/test/integration/service/concurrent-deployments.spec.ts

We had a check that prevented concurrent deployments in place, but it wasn't set correctly. The check was inside a transaction, so it would prevent some concurrent transactions. However, the lock would be released before the transaction ended, so we still had the original issue. The original problem was that concurrent deployments could be made, and they both would think that they were active.
The solution was simple. We flipped the code, and now the transaction is executed inside the check, so there can't be concurrent transactions at all

fix: handle concurrent requests correctly

---

comms/peer/test/Peer.integration.spec.ts
lambdas/src/apis/explore/controllers/explore.ts

So far, thumbnails had to be a url. We now want to allow content creators to set one of the uploaded files to be the scene's thumbnail. When this happens, the `explore` lambdas will convert that local path into a url

feat: add support for uploaded thumbnails

---

content/src/service/reporters/SegmentIoAnalytics.ts

This PR Fixes https://github.com/decentraland/catalyst/issues/56
As the payload sent to [Segment](https://segment.com/) was bigger than 32kb, then the error shown in issue #56 was being triggered. 
Remove pointers and files from the reporting to Segment.

Remove pointers and files from segment reporting

---

content/test/integration/syncronization/cluster-synchronization.spec.ts

This test that was modified was flaky. It was flaky because we hoped that servers 1 and 3 didn't learn about the updates in server 2 before it was shut down. Now, we:
1. Start only server 2
1. Deploy E2 on it
1. Shut it down
1. Start servers 1 and 3. 
By doing this, there is no way that servers 1 and 3 learn about E2 until server 2 is restarted

fix: avoid flakiness in test

---

content/src/controller/Controller.ts
content/src/storage/repositories/DeploymentsRepository.ts
content/test/integration/upload-and-download.spec.ts

In https://github.com/decentraland/catalyst/pull/226 we attempted to make pointers case insensitive. However, we missed to do so, because there was a check on `DenylistServiceDecorator` that was still case sensitive. 
Now, we fixed it 😃

fix: make pointers and deployedBy filters case insensitive

---

comms/lighthouse/rollup.config.js
comms/peer/rollup.config.js

In https://github.com/decentraland/catalyst/commit/aa7354aff8fb1caa91bf96c9e96cb712bf9cf134, we added a new linter. That linter was executed automatically, and it broke our build. We are now fixing it

fix: fix lighthouse build

---

comms/peer/src/PeerWebRTCHandler.ts
version.bzl

There is an error that appears from time to time in Rollbar:
`Uncaught TypeError: Cannot read property 'setRemoteDescription' of undefined`
It seems it can occur if there is a problem when building the RTCPeerConnection while performing a handshake to establish a WebRTC connection. Not sure what could cause that, but we should handle it using the normal error flow, so maybe the Peer library can try to recover.

fix: Undefined peer connection error

---

lambdas/BUILD.bazel
lambdas/src/Server.ts
lambdas/src/apis/profiles/EnsOwnership.ts
lambdas/src/apis/profiles/controllers/profiles.ts
lambdas/src/apis/profiles/routes.ts
lambdas/test/apis/profiles/EnsOwnership.spec.ts

Right now, we only have one endpoint `/profile/:ethAddress` that fetches one profile. In order to improve the performance of the client, we want to enabling fetching more than one in one request.
The new endpoint can be used like this `/profiles?id=EthAddress&id=EthAddress...`. We also added a `/profiles/:ethAddress`, so we could deprecate `/profile` in the future
Now, in order to do that, we made two big changes:
**ENSCache**
Previously, the cache was something like `Cache<Pair<EthAddress, Name>, Owned: boolean>`. Now, we changed it to: `Cache<Name, owner: EthAddress | null>`. 
**Queries to the graph**
We want to group as many calls as possible to the graph, so that the API loads faster. To do so, we are now simply fetching by chunks of 1000 names. The result with return a pair …

feat: enable fetching multiple profiles with one request

---

content/src/service/synchronization/ContentCluster.ts
lambdas/src/apis/profiles/EnsOwnership.ts

`slice` uses `(start, end)`, not `(start, count)`
Also, adding some logging to the content server start up process. Otherwise, it looks dead

fix: use slice correctly in profiles lambda

---

lambdas/BUILD.bazel
lambdas/src/BUILD.bazel
lambdas/src/Environment.ts
lambdas/src/Server.ts
lambdas/src/apis/collections/Utils.ts
lambdas/src/apis/collections/controllers/collections.ts
lambdas/src/apis/profiles/WearablesOwnership.ts
lambdas/src/apis/profiles/WearablesOwnershipFactory.ts
lambdas/src/apis/profiles/controllers/profiles.ts
lambdas/src/apis/profiles/routes.ts
lambdas/test/apis/profiles/EnsOwnership.spec.ts
lambdas/test/apis/profiles/WearablesOwnership.spec.ts
lambdas/test/apis/profiles/controller/profiles.spec.ts
tsconfig.json

We are now adding wearable sanitization to profiles. This means that we are filtering out wearables that are no longer owned by the user.
To do so, we added a cache that looks like this: `Cache<EthAddress, { wearable: Set<WearabledId>, lastFetched: Date }>`
We are storing the lastFetched data, so that we can return it later on another endpoint, where we will be able to request all wearables owned by the user.

feat: add wearables sanitization in profiles

---

content/src/service/synchronization/clients/ContentServerClient.ts

The fetch used for syncing was set to 2m by default. Now, we are making sure that the timeout is much smaller.
This is necessary because some servers might be really slow, and we want to make sure that the sync doesn't hang, waiting to fetch everything from them. Take into account that this call is a simple json fetch, should not take more than 20s

fix: set timeout for sync fetch

---

lambdas/src/apis/content-v2/controllers/translator.ts

We currently have a fallback in place where lambdas go to the old content server if they don't find something. 
We are not sure if this fallback is still being used, so we are adding some logs to it.

chore: add logs on fallback to old content

---

lambdas/BUILD.bazel
lambdas/src/apis/profiles/controllers/profiles.ts
lambdas/test/apis/profiles/controller/profiles.spec.ts

Right now, profiles metadata looks like this on the content server:
```
{
"avatars": [
{
"userId": "0xe100cf9c1d7a96a7790cb54b86658572c755ab2f",
"name": "Chamo",
"avatar": {
"bodyShape": "dcl://base-avatars/BaseMale",
"snapshots": {
"face": "QmQUEPgRA2kR5A8YsXngguA9g7zu5TurtNvABpYtyWQ8tJ",
"face128": "QmaYUWCBoVVWCGvGu6qgZiLvyNNYM9NseSspAzq2X74gEY",
"face256": "QmRW7cAP8UMuNH1xUF5giDvxU2wVVnNe3Jjz2CUii93v19",
"body": "QmNmLGQmsNMnbJ9mmPDoGEHBKufqtDjDLdTuNa9DREtegY"
},
....
},
]
}
```
If you look at the snapshots, those property values are file hashes. This means that clients that want to create/update profiles need to know exactly how the content server calculates hashes, so that they match the uploaded files. This isn't the best way to do it, since that hashing mechanism could change in …

feat: add support for file references inside profiles

---

commons/servers/metrics.ts
lambdas/src/Environment.ts
lambdas/src/Server.ts

The common practice is to register the route instead of the final url paths to normalize analysis.
This PR uses express' router to register the route instead of the final paths, `req.route.path`.
---
From express docs:
Contains the currently-matched route, a string. For example:
```
app.get('/user/:id?', function userIdHandler (req, res) {
console.log(req.route)
res.send('GET')
})
```
Example output from the previous snippet:
```
{ path: '/user/:id?',
stack:
[ { handle: [Function: userIdHandler],
name: 'userIdHandler',
params: undefined,
path: undefined,
keys: [],
regexp: /^\/?$/i,
method: 'get' } ],
methods: { get: true } }
```

fix: prevent flooding metrics and enable lambdas metrics endpoint

---

comms/lighthouse/test/idService.spec.ts

We have a flaky test that is failing a lot recently, so we increasing the timeout

chore: increase timeout in flaky test

---

lambdas/src/Environment.ts
lambdas/src/Server.ts
lambdas/src/apis/collections/controllers/collections.ts
lambdas/src/apis/collections/controllers/wearables.ts
lambdas/src/apis/collections/routes.ts
lambdas/src/apis/collections/types.ts
lambdas/src/apis/profiles/EnsOwnership.ts
lambdas/src/apis/profiles/EnsOwnershipFactory.ts
lambdas/src/apis/profiles/WearablesOwnership.ts
lambdas/src/apis/profiles/WearablesOwnershipFactory.ts
lambdas/src/utils/TheGraphClient.ts
lambdas/src/utils/TheGraphClientFactory.ts
lambdas/test/apis/collections/controller/wearables.spec.ts

We are now adding a new lambda: `/collections/wearables-by-owner/:ethAddress`
Based on the ethAddress, this lambda will return the ids of the owned wearables, with their respective amount. The payload will look like this:
```
type Response = { 
urn: WearableId,
amount: number,
definition?: Wearable
}[]
```
There is an optional property called `definition`. If the query param `includeDefinitions` is set on the request, then the wearable's definition will be included in the response.
**Note**
There was some refactoring done, in order to create `TheGraphClient`. This client will be in charge of handling all interactions with the graph. I noted that we were having the graph logic in lots of places, sometimes repeated, so I grouped everything under one class.

feat: adding wearables by owner endpoint

---

.eslintignore
comms/lighthouse/rollup.config.js

It seems with the update to a new version of typescript, it started to include some code in the build of the lighthouse monitor that failed when rollup would try to bundle it all together.
In order to fix this:
* Added 'this' as context to rollup (the code that typescript started to include used this in global scope, but checking if it is undefined or not).
* Removed 'ts' as plugin for the build, since the input of rollup is already transpiled

fix: Changing rollup config of monitor to fix lighthouse build

---

.circleci/config.yml

We are now building the lighthouse server as part of the CI, to catch any problems with the build process

fix: build lighthouse in CI

---

comms/peer/rollup.config.js
comms/peer/src/Peer.ts
comms/peer/src/types.ts
comms/peer/test/Peer.integration.spec.ts
version.bzl

We are not handling the status of peer connections when the server rejects because an id is taken. This should fix that. After this, we will need to update the peer library in Explorer.

fix: Added status handler for when id is taken, and properly connected it

---

lambdas/src/apis/profiles/EnsOwnership.ts
lambdas/src/apis/profiles/NFTOwnership.ts
lambdas/src/apis/profiles/WearablesOwnership.ts
lambdas/src/utils/TheGraphClient.ts
lambdas/test/apis/profiles/NFTOwnership.spec.ts

When we tried to generalize how NFT ownership was checked against the subgraph, we did it incorrectly. We had a cache that looked like this: `Cache<NFTId, Owner | null>`. This worked for names, because names are 1/1 NFTs, but this wouldn't work for wearables. This is because there can be hundreds of instances of the same wearable, each with a different owner.
To fix this, we are changing the cache to `Cache<{ethAddress, NftId}, owned: boolean>`

fix: make correct call to collections subgraph

---

lambdas/src/apis/collections/controllers/wearables.ts

Previously, if the user owned no wearables, then the request would fail

fix: don't fail when address owns no wearables

---

content/src/service/access/AccessCheckerForWearables.ts

Missing cast when trying to fetch items from thegraph

fix: wearables access check

---

content/src/migrations/scripts/1615568102704_fix_local_timestamp_index.ts

Fixes https://github.com/decentraland/catalyst/issues/274
Went from
```
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=239325.40..239383.85 rows=501 width=1660) (actual time=1459.488..1483.128 rows=501 loops=1)
->  Gather Merge  (cost=238683.68..283627.76 rows=385208 width=1660) (actual time=1425.201..1461.070 rows=6001 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Sort  (cost=237683.66..238165.17 rows=192604 width=1660) (actual time=1395.499..1397.691 rows=2026 loops=3)
Sort Key: dep1.local_timestamp DESC, dep1.entity_id DESC
Sort Method: top-N heapsort  Memory: 22717kB
Worker 0:  Sort Method: top-N heapsort  Memory: 22590kB
Worker 1:  Sort …
```

fix: adding correct index for local timestamp in deployments table

---

content/src/Environment.ts
content/src/helpers/FetcherFactory.ts

We are setting the origin in all requests made between content servers
The content server will know its own address based on the changes in https://github.com/decentraland/catalyst-owner/pull/44

feat: add origin information to the client

---

content/src/service/synchronization/SynchronizationManager.ts
content/src/service/synchronization/streaming/EventStreamProcessor.ts
content/src/service/synchronization/streaming/OnlyNotDeployedFilter.ts

Before this change, when a catalyst server performed synced with others, it would:
1. Learn new updates from other servers
1. Check and discard known deployments
1. Fetch all necessary files for each deployment
1. Perform the deployment internally (store it on the database)
The problem is that between step (1) and (3), the catalyst would lose the source of the deployment itself (the server where the update was learnt from). This forced the server to check against other random servers to see who might have those files.
We are now keeping the actual source from (1) to (3), so we can just query that server instead of trying to find one

refactor: use sync source for downloading files

---

content/src/storage/Repository.ts
package.json
yarn.lock

We are doing the following changes:
* Using the client version with [this fix](https://github.com/decentraland/catalyst-client/pull/77)
* Increasing the db-client pool size to 20
* Logging the amount of pending queries every 1 minute

fix: use client version with sync fix

---

lambdas/src/apis/profiles/NFTOwnership.ts
lambdas/src/apis/profiles/controllers/profiles.ts
lambdas/test/apis/profiles/NFTOwnership.spec.ts

We are now making a small change so that the `/profile` and `/profiles` endpoints continue to work, even if the subgraph is down.
In that scenario, all names and wearables will be considered valid and will remain unfiltered.

fix: make profiles work even if subgraph is down

---

lambdas/src/apis/collections/controllers/wearables.ts
lambdas/src/apis/collections/off-chain/OffChainWearablesManager.ts
lambdas/src/utils/TheGraphClient.ts

Previously, we expected collection ids to be the contract address of the collection. Now, we expect them to be the urn. For example:
`urn:decentraland:off-chain:base-avatars` or
`urn:decentraland:ethereum:collections-v1:xmash_up_2020`

fix: consider collection ids as urns

---

lambdas/src/apis/collections/controllers/collections.ts
lambdas/src/apis/collections/routes.ts
lambdas/src/apis/collections/types.ts
lambdas/src/utils/TheGraphClient.ts
lambdas/test/apis/collections/controller/collections.spec.ts

We are now adding a new `/collections` endpoint that will return all available collections.
The payload will look like this:
```
{
"collections": [
{
"id": "urn:decentraland:off-chain:base-avatars",
"name": "Base Wearables"
},
...
]
}
```
The idea was to make it like this, in order to easily add pagination/filters in the future consistently with other endpoints

feat: add new collections endpoint

---

Dockerfile
content/src/Environment.ts
content/src/service/access/AccessCheckerImplFactory.ts
content/test/integration/service/access/AccessCheckerImpl.spec.ts
content/test/manual/check-failed-deployments.spec.ts
lambdas/src/Environment.ts
lambdas/src/utils/TheGraphClientFactory.ts

We are making two changes here:
1. We are setting the version as 1.0.0, since we will be releasing a new version soon
2. We are making config consistent between lambdas & the content server. 
Now, by setting `COLLECTIONS_L1_SUBGRAPH_URL` or `COLLECTIONS_L2_SUBGRAPH_URL` as environment variables, both services will read the same config. Previously, each service's config had a different name

chore: make config consistent

---

content/src/Environment.ts
content/src/service/access/AccessCheckerForScenes.ts
content/src/service/access/AccessCheckerForWearables.ts
content/src/service/access/AccessCheckerImpl.ts
content/src/service/access/AccessCheckerImplFactory.ts
content/test/integration/service/access/AccessCheckerImpl.spec.ts
content/test/unit/service/access/AccessCheckerImpl.spec.ts
content/test/unit/service/validations/Validations.spec.ts
lambdas/src/utils/TheGraphClient.ts

We are now supporting both L1 and L2 to validate wearable ownership. But, we are checking one or the other, depending on the network in the urn

feat: use correct subgraph when validating wearables

---

lambdas/src/apis/collections/controllers/wearables.ts
lambdas/src/utils/SmartContentClient.ts

Uses[ 'X-Forwarded-Host' header ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)to build the url of the next page in the colection, instead of using host. As host is the local host from the nginx, but the forwarded host is the host that the original request was made to.
This change has been tested in peer-testing with the following configuration: https://github.com/decentraland/catalyst-owner/pull/46

fix: use X-Forwarded-Host header to create next url

---

commons/servers/metrics.ts
lambdas/src/Server.ts

We are now exposing metrics for all lambda endpoints. The main problem was that lambdas use routers, so we couldn't calculate the `req.route.path` correctly. 
The solution was to create a `Router` proxy (an ES6 Proxy) that would inject the metrics handler when each route is defined. 
How it looks now:

feat: expose all lambdas metrics

---

.eslintignore

Adding more files and folder to `.eslintignore`

fix: ignore eslint

---

content/src/entrypoints/run-local-database.ts
content/src/storage/Database.ts
content/src/storage/RepositoryFactory.ts

Before this change, the content server tried to connect to the database during startup. If it failed, it would connect as the root user, and create the database for itself. This was clearly an anti-pattern.
Thanks to https://github.com/decentraland/catalyst-owner/pull/53, we now have the ability to run psql scripts. We added a script that creates the database there, and stop giving that responsibility to the content server. That is done in https://github.com/decentraland/catalyst-owner/pull/55

chore: stop creating db in content server

---

content/src/Environment.ts
content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/Service.ts
content/src/service/ServiceFactory.ts
content/src/service/ServiceImpl.ts
content/src/service/caching/Cache.ts
content/src/service/caching/CacheManager.ts
content/src/service/caching/CacheManagerFactory.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/integration/E2EAssertions.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/service/pointers/NoOpPointerManager.ts

We are now adding a cache to the `/entities` endpoint. The `/deployments` endpoint is too generic, has too many filters and is usually used to get historic deployments, so we decided to had the cache directly to the `/entities` endpoint. 
To do so we added `getEntitiesByIds` and `getEntitiesByPointers` to the service, who will be in charge of caching.
This cache will help a lot in avoiding requests to the database. Since users tend to group together in the world, they will ask for the same scenes & profiles, so the cache makes a lot of sense

feat: adding cache for entities

---

content/README.md
content/src/migrations/scripts/1620070748842_remove_origin.ts
content/src/repository/extensions/DeploymentsRepository.ts
content/src/repository/extensions/FailedDeploymentsRepository.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/deployments/DeploymentManager.ts
content/src/service/errors/FailedDeploymentsManager.ts
content/src/service/synchronization/EventDeployer.ts
content/test/integration/E2EAssertions.ts
content/test/integration/errors/FailedDeploymentManager.spec.ts
content/test/integration/syncronization/error-handling.spec.ts
content/test/manual/check-failed-deployments.spec.ts
content/test/manual/service/reporters/SQSDeploymentReporter.spec.ts
content/test/unit/service/errors/NoOpFailedDeploymentsManager.ts
yarn.lock

This PR removes the origin timestamp and origin server url from the deployments table and the corresponding endpoints responses.
Changes:
- <b> \* Breaking change \*</b> Add DB migration script to remove the correct columns and indexes in `deployments` and `failed_deployments` 
- Remove `origin_server_url` and `origin_timestamp` from the repository queries for deployments
- Remove `origin_server_url` and `origin_timestamp` from the repository queries for failed_deployments
- Add doc on how to run tests 
- Add doc on how to connect to db locally
- Update `dcl-catalyst-client` version to `5.0.1`
Fixes #273

Breaking Change: Remove origin url and timestamp from deployments

---

content/src/migrations/scripts/1620221157277_add_lowercase_deployer_index.ts
content/src/repository/extensions/DeploymentsRepository.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/unit/repository/DeploymentsRepository.spec.ts
content/test/unit/repository/MockedDataBase.ts

This PR:
- Introduces a new index for deployer_address for the lowercase of the column, since we'll be searching ignoring case, but saving values as they come
- Creates a test suite for DeploymentRepository, achieving ~100% coverage mocking the database
- Fixes a bug in the `createOrClause` method where the timestamp type was hardcoded and didn't change based on the filter type
- Modifies the query for deployer_address so that it looks for the LOWER of the incoming address
- Modifies some queries from multiline to single line to make them more testable
Fixes #291

Fix: Deployed by filter capitalization

---

lambdas/src/utils/SmartContentClient.ts
lambdas/src/utils/TheGraphClient.ts

When querying for wearables ownership, we used to have an optimization in place so that we only queried the subgraph that the wearables belonged to. For example, if a wearable was created in ethereum, we would only check the L1 subgraph.
This optimization had a bug though, that used the urn's protocol to determine the correct subgraph to use. The problem was that a "mumbai" (matic's testnet) urn would not match any of the layers used (only "mainnet" or "matic").
Since we want to support assets that move from one chain to the other in the near future, we will just remove this optimization, instead of trying to fix it. We were going to remove it anyways to support this new need.

fix: remove bugged optimization

---

comms/lighthouse/BUILD.bazel
comms/lighthouse/src/configService.ts
comms/lighthouse/src/layersService.ts
comms/lighthouse/src/routes.ts
comms/lighthouse/src/server.ts
comms/lighthouse/src/simpleStorage.ts
comms/lighthouse/test/configService.spec.ts

**tl;dr;**
* We are adding a new source of configuration. This new source is an endpoint that is polled every 15 min
* We are adding a new endpoint `/config` to read server's the current configuration
* We are adding listeners to the `configService`, so other services can react to the change in config. By doing this, we are avoiding the need for whole server restarts
We are now giving a lot more love to the `configService`. There will be 4 different sources for configuration, with the following precedence:
```
Environment config >> storage config >> global config >> defaults
```
The main change is that now, there is a global configuration. This configuration can be controlled by the foundation, but it can be easily overridden by catalyst owners. This approach will make it easier to test …

feat: add support for global config

---

content/src/migrations/Helper.ts
content/src/migrations/scripts/1623671909421_delete_failed_deployments.ts

All prod catalysts have a subset these same failed deployments. 
```
'QmTBPcZLFQf1rZpZg2T8nMDwWRoqeftRdvkaexgAECaqHp',
'QmXibTSJ6wBpXiG3gc2RND9Z6k75AssvHrwpdCVZNjVGbt',
'QmVktBsdgFSQHs68rDJCZrHQgCUFhyJ4QEiGPWivrenpcd',
'QmaG2d2bsb4fW8En9ZUVVhjvAghSpPbfD1XSeoHrYPpn3P',
'QmeT7cLXPPrNZk6vUis4Zut7ArXJ4rAfCh6LyMb8C4t8gA',
'QmTjLddBe7qxyabcxCWNaYKUyro8uh76PCmB6ASKSwGtCA',
'QmfEKyT78Pb5rAGaASLPPCyZbUn8rVY4YqKcdtRpYFVzbZ',
'QmPiUvhZ6HkDxJLZ65t3wkwrkfEKc2NScPqnSzSZCqSfUC',
'Qma7kh4ooweKroG5PEDgrm4dVnKuxPqBexnFkDhDVBzG4P',
'QmUKsDTqsVnxxcQT4g5ewGjtFF6Btc7ofbGAbyfcdRkJw4',
'QmYzeUZASCJVaD16dZxTr9Kf7oinGtaebqNghEaRouqaNt'
```
The first 9 of these deployments were deployed in `decentraland.org.cn`, back when it was part of the DAO-approved list of catalysts. The problem is that the server didn't work …

chore: remove entries from failed deployments

---

content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/synchronization/EventDeployer.ts
content/src/service/synchronization/clients/ContentServerClient.ts
content/src/service/validations/Validations.ts
content/test/helpers/service/EntityTestFactory.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/legacy-entities.spec.ts
content/test/integration/upload-and-download.spec.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts
content/test/unit/service/EntityFactory.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/service/validations/Validations.spec.ts

Before this change, the entity file had to be named `entity.json`. We required this naming so that we could find it easily. The thing is, that we were already hashing the files, so we could just find it by its hash. 
By doing this change, we can now forget about names when deploying and just send the files without any other considerations.

feat: avoid the need to name the entity file

---

content/src/controller/Controller.ts
content/src/service/synchronization/clients/ContentServerClient.ts
content/test/integration/Server.spec.ts

We are now setting a limit for high offsets. The `lastId` property can be used if necessary

fix: fail with high offsets

---

commons/servers/QueryParameters.ts
content/src/controller/Controller.ts
content/src/service/deployments/DeploymentManager.ts
content/test/integration/controller/deployment-pagination.spec.ts

We realized that the the `next` field in the `/deployments` endpoint did not include the query param `fields`, even when it was included in the original request. We are now fixing that

fix: add fields to next link

---

lambdas/src/apis/explore/controllers/explore.ts

We were asking the wrong cache for the last update timestamp, and it could happen that the other cache wasn't initialized, leading to an error

fix: ask last update to correct cache

---

content/src/Server.ts
content/src/controller/Controller.ts
content/test/integration/Server.spec.ts
content/test/integration/TestServer.ts
content/test/integration/controller/deployment-pagination.spec.ts
content/test/manual/check-failed-deployments.spec.ts
docs/content-server-api/CONTENT_SERVER_API.md
docs/content-server-api/pointer-changes/get.md

For some reason, `/failedDeployments` and `/pointerChanges` were not consistent in casing with the other endpoints. We are taking a first step towards changing that

fix: make endpoint casing consistent

---

comms/lighthouse/src/peers/archipelagoService.ts
comms/lighthouse/src/peers/peerMessagesHandler.ts
comms/lighthouse/src/peers/protocol/messageTypes.ts
comms/lighthouse/test/archipelagoService.spec.ts
package.json
yarn.lock

This PR adds support for receiving the preferred island through the heartbeat, and forwarding it to archipelago.
Closes #571.
See also: https://github.com/decentraland/archipelago/issues/32

feat: Prefered island support

---

content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts
content/test/unit/service/Service.spec.ts

In https://github.com/decentraland/catalyst/pull/579 we removed the Segment.io reporter since it wasn't being used anymore. With that change, we can now get read of the origin that we've been passing around the code everywhere.
This "origin" property was only used in that reporter, so it doesn't make much sense to keep it around

refactor: remove origin

---

content/src/service/ServiceImpl.ts
content/src/service/auth/Authenticator.ts
content/src/service/auth/AuthenticatorFactory.ts
content/src/service/validations/Validations.ts
content/src/service/validations/ValidationsFactory.ts
content/test/integration/service/access/AccessCheckerImpl.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/service/access/AccessCheckerForProfiles.spec.ts
content/test/unit/service/access/AccessCheckerForScenes.spec.ts
content/test/unit/service/validations/Validations.spec.ts

We are simply moving the network from `Validations` into the `Authenticator`, so we can reduce coupling and make `Validations` easier to modify

refactor: move eth network to authenticator

---

content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/synchronization/EventDeployer.ts
content/test/helpers/service/MockedMetaverseContentService.ts

We are now making the service simpler by removing different versions and just passing the deployment context as a parameter

refactor: make service simpler

---

content/src/denylist/DenylistServiceDecorator.ts
content/src/service/ServiceImpl.ts
content/src/service/access/AccessCheckerForWearables.ts
content/src/service/snapshots/SnapshotManager.ts
content/src/service/validations/Validations.ts
content/src/service/validations/Validator.ts
content/src/service/validations/validations/ValidationsV3.ts
content/src/service/validations/validations/ValidationsV4.ts
content/test/integration/E2EAssertions.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/service/access/AccessCheckerForWearables.spec.ts
content/test/unit/service/validations/Validations.spec.ts
package.json
yarn.lock

We are now adding support for v4 entities. This new version of entities will have IPFS v2 hashes instead of the current ones.
As part of this change we are also:
* Making snapshots use IPFS hashes
* Supporting wearable reverts with IPFS hashes

feat: add support for ipfs hashing

---

content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/repository/extensions/DeploymentsRepository.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/validations/Validations.ts
content/src/service/validations/Validator.ts
content/test/integration/E2ETestUtils.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts
content/test/unit/repository/DeploymentsRepository.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/service/validations/Validations.spec.ts

Thanks to https://github.com/decentraland/catalyst/pull/595, we now have the entity's version inside the entity itself. So we don't need to have it on the audit info anymore. Yay

refactor: remove the need for the version on the audit info

---

content/src/service/ServiceImpl.ts
content/test/unit/service/Service.spec.ts
lambdas/src/Server.ts

In https://github.com/decentraland/catalyst/pull/462 we added a cache to store entities from pointers, but we didn't consider the case when a pointer of a scene is null, so we are adding support on the cache for that case.
fixes https://github.com/decentraland/catalyst/issues/629

Add null values to cache

---

comms/lighthouse/src/peers/auth.ts
content/package.json
package.json

This changes are required to successfully start services that currently don't (lighthouse and content).
- Start content server
```
yarn workspace @catalyst/content-server start:server
```
- Start lighthouse server
```
yarn workspace @catalyst/lighthouse-server start:server
```

fix: workspace dependencies references and fix start scripts

---

.vscode/settings.json
content/package.json
content/src/Environment.ts
content/src/Server.ts
content/src/repository/RepositoryQueue.ts
content/src/service/ServiceFactory.ts
content/src/service/ServiceImpl.ts
content/src/service/caching/CacheManager.ts
content/src/service/synchronization/EventDeployer.ts
content/src/service/synchronization/SynchronizationManager.ts
content/src/service/validations/Validations.ts
content/src/service/validations/Validator.ts
content/src/service/validations/validations/ValidationsV3.ts
content/src/service/validations/validations/ValidationsV4.ts
content/test/unit/service/validations/Validations.spec.ts
yarn.lock

Add a new validation for V3 and V4 entities which rate limits the number of deployments. It only allows making a deploy per pointer per TTL configured and a max amount of deployments too.

Add a rate limit for deploying profiles

---

content/.gitignore
content/src/service/ServiceImpl.ts
content/src/service/ServiceStorage.ts
content/src/service/validations/Validations.ts
content/src/service/validations/Validator.ts
content/src/service/validations/validations/ValidationsV4.ts
content/src/storage/ContentStorage.ts
content/src/storage/FileSystemContentStorage.ts
content/src/storage/S3ContentStorage.ts
content/test/unit/service/validations/Validations.spec.ts
content/test/unit/storage/MockedStorage.ts

Introduces entity v4 deployment size validation.
Takes into account all content files and not just the uploaded files in current deployment.
Resolves #198

feat: validate v4 entities size including previous deployments

---

content/src/service/validations/Validations.ts
content/src/service/validations/Validator.ts
content/src/service/validations/ValidatorFactory.ts
content/src/service/validations/validations/ValidationsV4.ts
content/test/unit/service/validations/Validations.spec.ts

- Increase total size limit for wearables to 3 MB.
- Set model size limit for wearables to 2MB (without taking into account the thumbnail image).

feat: add wearables size validation with new limits

---

Dockerfile

With this change dependencies will be cached when there are no changes in any `package.json` and code will always be rebuilt.

fix: prevent docker to cache stages that need to be run and cache dependencies stage

---

content/src/logic/snapshots-queries.ts
content/src/migrations/scripts/1620152961576_add_deleter_indexes.ts
content/src/migrations/scripts/1639480263808_snapshot_index.ts

```
content=> EXPLAIN ANALYZE SELECT entity_id, entity_pointers, date_part('epoch', local_timestamp) * 1000 AS local_timestamp FROM deployments d WHERE d.deleter_deployment IS NULL AND entity_type = 'wearable' ORDER BY d.local_timestamp DESC;
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=1622.02..1624.85 rows=1133 width=131) (actual time=3.608..4.607 rows=1244 loops=1)
Sort Key: local_timestamp DESC
Sort Method: quicksort  Memory: 379kB
->  Index Scan using deployments_entity_type_index on deployments d  (cost=0.42..1564.55 rows=1133 width=131) (actual time=0.042..2.179 rows=1244 loops=1)
Index Cond: (entity_type = 'wearable'::text)
Filter: …
```

fix: snapshot indexes

---

content/src/Environment.ts

With this change, we are allowed to deploy 300 profiles per minute per Catalyst.

Increase rate limit for deploying profiles

---

content/src/service/Server.ts
content/test/unit/service/Service.spec.ts

Remove deprecated CamelCase endpoints:
- `/pointerChanges` => `/pointer-changes`
- `/failedDeployments` => `/failed-deployments`

Remove deprecated CamelCase endpoints

---

lambdas/src/Environment.ts
lambdas/src/apis/collections/off-chain/OffChainWearablesManager.ts
lambdas/test/apis/collections/off-chain/OffChainWearablesManager.spec.ts

Deploying changes for the off chain wearables is taking a long time because results are cached for one day, making it difficult to check if what was deployed is correct, and also for testing and iterating. The goal of this PR is to reduce that time to a number that helps with these issues, while not impacting the catalyst performance.
- Reduce the default time for off chain wearables cache refresh from `1 day` to `15 minutes`

chore: reduce off chain refresh time

---

content/src/components.ts
content/src/logic/deployments.ts
content/src/ports/failedDeploymentsCache.ts
content/src/service/ServiceImpl.ts
content/src/service/synchronization/SynchronizationManager.ts
content/src/service/validations/server.ts

Update failed deployment error description when retry task fails to fix it.
Fixing a failed deployment will be ignored when there are newer entities with same pointer and it will be removed from the cache.

feat: update error when failed deployment retry fails

---

content/package.json
content/src/Environment.ts
content/src/components.ts
content/src/controller/Controller.ts
content/src/controller/ControllerEntityFactory.ts
content/src/logic/database-queries/deployments-queries.ts
content/src/ports/denylist.ts
content/src/ports/fs.ts
content/src/repository/extensions/DeploymentsRepository.ts
content/src/service/Service.ts
content/src/service/ServiceFactory.ts
content/src/service/ServiceImpl.ts
content/src/service/deployments/DeploymentManager.ts
content/src/service/deployments/deployments.ts
content/src/service/deployments/types.ts
content/src/service/pointers/pointers.ts
content/src/service/snapshots/SnapshotManager.ts
content/src/types.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/integration/service/deployments/pointer-changes-check.spec.ts
content/test/unit/ports/denylist.spec.ts
content/test/unit/repository/DeploymentsRepository.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/service/deployments/deployments.spec.ts
yarn.lock

This PR introduces a new denylist for entity ids.
The list is saved in disk in a file in the storage folder, where each line is an entity id.
The denylist is a component that given a string will return wether it's delisted or not.
Closes #916 
The `/deployments` `/entities/:type` and `/audit` endpoints filter out the entity if a given id is denylisted.
The `/content/:hash/active-entities` doesn't return a found entity if it's denylisted
The `/pointer-changes` endpoint doesn't return denylisted ids

New denylist

---

content/src/Environment.ts
content/src/components.ts
content/src/controller/Controller.ts
content/src/metrics.ts
content/src/ports/deployRateLimiterComponent.ts
content/src/ports/fetcher.ts
content/src/ports/rateLimitDeploymentCacheMap.ts
content/src/service/ServiceFactory.ts
content/src/service/ServiceImpl.ts
content/src/service/validations/server.ts
content/src/types.ts
content/test/unit/service/Service.spec.ts

Expand the rate limit when deploying functionality to all entity types, it was used only for profiles. 
It has a default configuration, but it can be overwritten by the owner of the catalyst.

Rate limit when deploying any entity type

---

docs/lambdas-server-api/health/get.md
lambdas/src/apis/status/PeerHealthStatus.ts
lambdas/src/apis/status/health.ts
lambdas/test/apis/status/PeerHealthStatus.spec.ts
lambdas/test/apis/status/health.spec.ts

Prevent client issues trying to fetch content from a server that is bootstrapping
Closes https://github.com/decentraland/catalyst/issues/925
Closes https://github.com/decentraland/catalyst/issues/926
- Mark content server as `Healthy` only when Syncing. Otherwise it would be `Unhealthy`, like when Bootstrapping
- Add attribute `readyToUse` to the health route to make it easy for a load balancer to understand the health of the whole system
- Make calls to the comms, lambda, and content server in parallel instead of serial
- Create `PeerStatus` type for the peer health response, as it is not possible to create some type with the form `Record<string, HealthStatus> & { readyToUse: boolean }`
- https://github.com/decentraland/catalyst-api-specs/pull/24
What types of changes does your code …

feat: set content server as healthy only when it is Syncing

---

.circleci/config.yml

Use CircleCI convenience docker images, instead of deprecated ones. These images should be cached by CircleCI (avoid downloading them every job).
(ref: https://circleci.com/developer/images?imageType=docker)

chore: use circleci convenience images

---

content/src/controller/Controller.ts
content/src/service/Server.ts
content/test/integration/controller/content.spec.ts

The `getContent` controller was being used instead of the `headController` for the `HEAD /contents/{hashId}` endpoint.
This is because the `HEAD` method was registered after the `GET` for the same route, and the way Express works
Fixes https://github.com/decentraland/catalyst/issues/938
- Change the order of the registered `HEAD` and `GET`
- Add the missing `res.send()` to the `headController`

fix: use headContent controller for HEAD contents endpoint

---

lambdas/src/apis/status/routes.ts
lambdas/test/apis/status/PeerHealthStatus.spec.ts

Send a status code `503` for indicating that a catalyst is unhealthy if some of its services is not `Healthy`
Closes https://github.com/decentraland/catalyst/issues/939
- Status code `503` when some unhealthy service in `GET /lambdas/health` endpoint
Docs: https://github.com/decentraland/catalyst-api-specs/pull/26

feat: set status 503 when some service is unhealthy

---

.circleci/config.yml
.eslintignore
.gitignore
content/jest.globalSetup.ts
content/jest.globalTeardown.ts
content/jest.setupFilesAfterEnv.ts
content/package.json
content/printApiCoverage.js
content/reportApiCoverage.js
yarn.lock

Add an option to create an API Coverage Report after running tests
Helps with:
- https://github.com/decentraland/catalyst/issues/895
Create an API Coverage Report on the console when tests run with the `API_COVERAGE=true` environment variable.
- Add dev libraries `chalk` and `columnify` to create a beautiful report table
- Add report code to Jest setup files and avoid touching any production related code
- Some code is written in a hacky way to setup a middleware from the Jest file
- A temporary coverage file is generated to pass through the different Jest file, as tests run in sandbox environments. This may prevent running the report on a CI with parallel processing, making it available only when running locally or on a serial way.
- Jest has a `reporter` functionality but it didn't work …

chore: add api coverage for the content server

---

content/src/service/Server.ts
content/test/integration/controller/audit.spec.ts
content/test/integration/controller/available-content.spec.ts
content/test/integration/controller/content.spec.ts
content/test/integration/controller/entities.spec.ts
content/test/integration/controller/snapshot.spec.ts
content/test/integration/controller/status.spec.ts

Add missing tests to cover all API endpoints for the content server
- Add tests
- Bump `catalyst-api-specs` version
- Modify `OpenApiValidator` middleware
- Validate responses on the CI
- Ignore undocumented endpoints
- Ignore `/entities` path as it leads to validation errors while testing other paths
- Add middleware to log `OpenApiValidator` errors

test: add missing tests for the content server

---

lambdas/src/utils/TheGraphClient.ts

This PR adds support for items of type `emote`. Currently they share the same schema as a `wearable` with an extra `emoteDataV0` property. Eventually they will move to their own schema and at that point we will probably need to treat them different to avoid runtime errors, but for now it's safe since everything you would expect on a wearable exist on an emote.
Added the `emote_v1` to the list of accepted types in the GraphQL queries.

feat: add support for emotes

---

content/package.json
content/src/Environment.ts
content/src/service/validations/validator.ts
yarn.lock

This new version includes the fixed ADR 45 timestamp.

chore: bump content-validator version to 1.4.0

---

lambdas/src/Environment.ts
lambdas/src/Server.ts
lambdas/src/apis/collections/types.ts
lambdas/src/apis/third-party/controllers/third-party.ts
lambdas/src/apis/third-party/routes.ts
lambdas/src/utils/TheGraphClient.ts
lambdas/src/utils/TheGraphClientFactory.ts

Adds `/third-party-integrations` endpoint.
It will query The Graph third party registry subgraph and return the list of integrations.

feat: fetch third party integrations from subgraph endpoint

---

lambdas/src/apis/collections/controllers/wearables.ts
lambdas/src/apis/collections/types.ts
lambdas/src/utils/TheGraphClient.ts
lambdas/src/utils/third-party.ts
lambdas/test/apis/collections/controller/wearables/wearables-by-owner.spec.ts

Adding TPW support to `GET /lambdas/collections/wearables-by-owner/:address?collectionId=THIRD_PARTY_URN` endpoint. 
Added behaviour: 
- When a `collectionId` is present.
- Query The Graph for a TPR (third party resolver).
- Fetch wearables from that TPR API (using same `collectionId` and given user `address`)

feat: fetch wearables from third party resolver API

---

lambdas/src/apis/collections/types.ts
lambdas/src/utils/TheGraphClient.ts

Add `name` to third-party collections lambda and remove the `id` inside the `metadata` which is not being used. 
The explorer need it:

Feat: add name to tp collections

---

content/src/Environment.ts
content/src/ports/postgres.ts

The changes allow for decreasing the connection idle timeout for regular (non-streaming) queries and at the same time to run long-running streaming queries in a connection outside of the connection pool and configured with its own independent timeout.
Fixes #1040
i.e.
- Decreased default connection query_timeout for queries.
- Introduced new env variable to configure query_timeout for streaming queries.
- Changed `postgres#streamQuery` so that it uses fresh direct connections (outside of the connection pool) and with a separate query_timeout.
- New feature (non-breaking …

chore: decrease query timeout

---

content/src/components.ts
content/src/service/validations/validator.ts
content/src/types.ts

Extract externalCalls as a WKC so it's possible to mock individual checks of the content-validator.

refactor: make externalCalls a component

---

content/src/logic/database-queries/deployments-queries.ts
content/test/integration/service/deployments/deployment-entity-overlap.spec.ts

New tests have been added in `deployment-entity-overlap.spec.ts` to verify some scenarios that could happen during scene deployments overlapping with previous ones:
- When new scene is deployed on overlapping parcels, then new deployment removes previous scenes from orphaned parcels
- When scene is deployed, then server checks for permissions
- When parcel changes owner, then new deployment by new owner succeeds and removes previous scenes from orphaned parcels
- All new and existing tests passed.

fix: correct handling when deploying overlapping scenes with a new owner

---

.github/workflows/release.yml

Update the gh-action-release to version 0.2.0:
- Fix an issue regarding retrieving the repo owner (necessary for making requests to the Github API)
- Include dry run option
- Update the gh-action release version
- Change the release workflow to include the dry run parameter

chore: update gh-action-release 0.1.0 -> 0.2.0

---

.github/workflows/release.yml

gh-action-release@0.2.2 includes:
- Add the parenthesis to the regex for the commit message
- Add the multiline option to the regex
Closes #1101

chore: bump gh-release-action to fix dependabot commits issues

---

.gitignore
content/src/controller/Controller.ts

A `500` error is being returned when calling `/content/entities/active/collections/{collectionUrn}` with a collection urn that is invalid.
Fixes #1048 
- Catch the `500` error retrieved from `parseUrn`
- Print it
- Let the previous method get the invalid result and return a `400`

fix: return 400 instead of 500 when invalid urn

---

lambdas/src/utils/TheGraphClient.ts
lambdas/test/__fixtures__/wearables-by-owner-matic-p1.json
lambdas/test/__fixtures__/wearables-by-owner-matic-p2.json
lambdas/test/utils/the-graph-client.spec.ts

Given the hard restriction from TheGraph that doesn't support pagination beyond 5000 records, this PR implements the alternative approach suggested [here](https://thegraph.com/docs/en/developer/graphql-api/#example-using-and-2
).

fix: support pagination over result sets larger than 5000 records

---

content/src/ports/activeEntities.ts
content/src/service/ServiceImpl.ts
content/test/integration/controller/active-pointers.spec.ts

When managing the active pointers, update method is not returning a promise which makes it impossible to handle its asynchronous behaviour. It's having some impact on the tests, generating a race condition when querying the database

fix: make update return a promise

---

content/src/logic/hashing.ts
content/src/service/EntityFactory.ts
content/src/service/ServiceImpl.ts
content/test/integration/logic/delete-unreferenced-files.spec.ts
content/test/integration/resources/QmYfCVBv7PJCcBh3AutAzNesdGZVKUEd8KCc8Jh1Y8ba4u
content/test/integration/resources/QmbNcPuVAq6Dv821kfFnyaM59Go3xCeBMnSxYRSHEpwWeF
content/test/integration/service/deployments/old-entity-synced.spec.ts

Errors found:
```
2022-06-30T17:24:06.660Z [ERROR] (ServiceImpl): There was an error parsing the entity: Error: Object has an invalid version     “There was an error parsing the entity: Error: Object has an invalid version”
Trace
at Object.error (/Users/agustina/Documents/dcl/catalyst/node_modules/@well-known-components/logger/dist/helpers.js:53:37)
at ServiceImpl.deployEntity (/Users/agustina/Documents/dcl/catalyst/content/dist/src/service/ServiceImpl.js:51:32)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async deployDownloadedEntity (/Users/agustina/Documents/dcl/catalyst/content/dist/src/service/synchronization/deployRemoteEntity.js:45:34)
at async deployEntityFromRemoteServer …
```

fix: revert changes to support syncing old entities

---

content/src/service/ServiceImpl.ts

This change will prevent printing stack trace when a synced deployment fails while the content server bootstraps. Since the message error we are logging is good enough to realized what happened during the deployment, we want to avoid flooding logs with redundant information.
[Fixes # 984](https://github.com/decentraland/catalyst/issues/984)
- Call LOGGER.warn instead of LOGGER.error function to avoid printing stack trace on failures

fix: remove stacktrace when synced deployment fails

---

content/package.json
content/src/service/Server.ts
content/test/integration/TestProgram.ts
content/test/integration/controller/active-entities.spec.ts
content/test/integration/controller/active-entity-by-content-hash.spec.ts
content/test/integration/controller/deployment-fields.spec.ts
content/test/integration/controller/deployment-pagination.spec.ts
content/test/integration/logic/delete-unreferenced-files.spec.ts
content/test/integration/syncronization/cluster-synchronization.spec.ts
content/test/integration/syncronization/error-handling.spec.ts
content/test/integration/syncronization/failed-deployments.spec.ts
content/test/integration/syncronization/node-onboarding.spec.ts
content/test/integration/upload-and-download.spec.ts
lambdas/package.json
lambdas/src/apis/collections/controllers/collections.ts
lambdas/src/apis/collections/controllers/emotes.ts
lambdas/src/apis/collections/controllers/wearables.ts
lambdas/src/apis/collections/off-chain/OffChainWearablesManager.ts
lambdas/src/apis/explore/controllers/explore.ts
lambdas/src/apis/profiles/controllers/profiles.ts
lambdas/src/apis/status/health.ts
lambdas/src/utils/SmartContentClient.ts
lambdas/test/apis/collections/controller/wearables/wearables-by-owner.spec.ts
lambdas/test/apis/collections/controller/wearables/wearables.spec.ts
lambdas/test/apis/collections/off-chain/OffChainWearablesManager.spec.ts
lambdas/test/apis/profiles/controller/profiles.spec.ts
yarn.lock

This PR relates to [Issue (#1119)](https://github.com/decentraland/catalyst/issues/1119) and [Catalyst-Client PR](https://github.com/decentraland/catalyst-client/pull/295). It implements the functions removed from the shared client exposed by `Catalyst Client` since they are only being used in this project.
This depends on the version upgrade to be done once the PR on Catalyst-Client is merged.
[Issue (#1119)](https://github.com/decentraland/catalyst/issues/1119) 
- No behavior changes expected.

refactor: implement unshared functions after removing them from shared client

---

content/src/ports/activeEntities.ts
content/test/unit/service/Service.spec.ts

It fixes how the content server stores and retrieves Entities by Ids or Pointers.
Reason of the issue: we had keys mixing uppercases and lowercases on the cache.
Also, it fixes a corner case where on (`/content/entities/active` endpoint):
* If you try to get an entity by Id, the client needs to send that Id always in lowercases
* If the client at some point miss parsing the Id to lowercase and send it with at least one letter in uppercase, then the cache breaks
* Now the client can send the id in lower or uppercases and the content server internally will treat them as they were always in lowercases, so the cache should not break again because of this

fix: pointers and ids retrieval from content by normalizing cases

---

content/src/ports/activeEntities.ts
content/test/unit/ports/activeEntities.spec.ts
content/test/unit/service/Service.spec.ts

It fixes how the content server stores and retrieves Entities by Ids or Pointers.
Reason of the issue: we had keys mixing uppercases and lowercases on the cache.
- Now the entities pointers are saved and retrieved from the cache always using lowercases
- Add 2 tests to verify that the issue is solved
- Also this solves the following edge case while keeping the ids cache key case sensitive:
```
1. If you try to get an entity by Id, the client needs to send that Id always in lowercases
2. If the client at some point miss parsing the Id to lowercase and send it with at least one letter in uppercase, then the cache breaks
3. This fix prevents corrupting the cache when an invalid id is asked to the catalyst, meaning that every time the client sends a valid id the peer answers with the proper …
```

fix: normalize pointers on cache for active entities

---

content/package.json
content/src/service/ServiceImpl.ts
yarn.lock

This PR moves the validation related to ADR-45 to the content server. Therefore, also contains an upgrade of the content-validator package.
Closes # (1201)
Remove the validation related to the ADR-45 from the ServiceImpl and implement it on content-validator package. No behavior changes expected.

refactor: move ADR45's validation to content-validator

---

content/src/controller/Controller.ts
content/src/logic/query-params.ts
content/src/types.ts
content/test/integration/controller/deployment-pagination.spec.ts

This PR adds support to different array query params formats:
* param=1&param=2 => [1, 2]
* param[]=1&param[]=2 => [1,2]
* param[1]=1&param[0]=2 => [2,1]

fix: array query params handling to support param[] format

---

content/package.json
lambdas/package.json
yarn.lock

This PR just bumps the `content-validator` version to run scenes validations in parallel during deployments.
Fixes #199 
- Bootstrap ignoring all entities but scenes on `peer.decentraland.zone` using current validations which lasted `2 minutes and 15 seconds`:
- Bootstrap ignoring all entities but scenes on `peer.decentraland.zone` using current validations which lasted `1 minute`:
In the current `zone` context, these parallel validations result in a reduction of more than fifty percent in scenes deployment time. But this improvement is related to the amount of failed scenes in the chain.

chore: bump content-validator version to validate scenes in parallel

---

lambdas/src/utils/SmartContentClient.ts

Fixes SmartContentClient to always return aggregated type with `getContentUrl`.

fix: getContentUrl on SmartContentClient

---

content/jest.globalSetup.ts
content/src/ports/activeEntities.ts
content/test/integration/E2ETestEnvironment.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/controller/active-entities.spec.ts
content/test/integration/controller/active-entity-by-content-hash.spec.ts
content/test/integration/controller/active-pointers.spec.ts
content/test/integration/controller/audit.spec.ts
content/test/integration/controller/available-content.spec.ts
content/test/integration/controller/content.spec.ts
content/test/integration/controller/deployment-fields.spec.ts
content/test/integration/controller/deployment-pagination.spec.ts
content/test/integration/controller/entities.spec.ts
content/test/integration/controller/entity-metadata.spec.ts
content/test/integration/controller/status.spec.ts
content/test/integration/ports/deployer/concurrent-deployments.spec.ts
content/test/integration/ports/deployer/deployment-filters.spec.ts
content/test/integration/ports/deployer/metadata-schema-validations.spec.ts
content/test/integration/ports/deployer/old-entity-synced.spec.ts
content/test/integration/ports/deployer/order-check.spec.ts
content/test/integration/ports/deployer/same-timestamp-check.spec.ts
content/test/integration/ports/snapshotStorage.spec.ts
content/test/integration/simpleTestEnvironment.ts
content/test/integration/syncronization/batch-deployer.spec.ts

Create a default database (one per runner) and create a default server pointing to such database once per test suite.

chore: for simple test cases use createDefaultServer

---

.circleci/config.yml
content/package.json
content/src/service.ts

I notice using `--expose-gc and --logHeapUsage` there is no more out of memory, which I think indicates we are not dealing with a memory leak here, our tests just take a lot of memory!

chore: increase max-old-space for tests

---

content/src/Environment.ts
lambdas/src/Environment.ts

TheGraph hosted service is going EOL. This PR replaces all links that go to hosted service with a new link that targets our own subgraph worker. This worker will handle requests for all subgraphs redirecting to TheGraph studio or satsuma depending on availability
Replace the subgraphs urls with the new ones to point to the subgraph worker instead of directly to thegraph hosted service

feat: update  subgraphs links

---

content/package.json
content/src/controller/handlers/get-content-handler.ts
content/src/controller/handlers/get-entity-image-handler.ts
content/src/controller/handlers/get-entity-thumbnail-handler.ts
content/src/controller/utils.ts
content/test/integration/controller/entity-metadata.spec.ts
package.json
yarn.lock

feat: return Content-Type header with the mimeType of the file

---

.vscode/settings.json
content/src/controller/utils.ts

fix: destroy stream to prevent leaking file descriptors

---

content/src/controller/handlers/get-content-handler.ts

This PR changes the `GET /content/contents` endpoint to check a query-string param instead of a Header to decide whether it should calculate a content-type or return the default one used by the sync.
This is a fix since CDNs caches requests based on URL path and does not acknowledge headers while doing so.

fix: opt-in of Content-Type header on /contents endpoint

---

content/src/service/garbage-collection/GarbageCollectionManager.ts
content/test/integration/service/garbage-collection/garbage-collection.spec.ts

This PR prevents the garbage collection from removing default profiles from the database whenever it runs.

fix: prevent garbage collection from removing default profiles

---

content/package.json
yarn.lock

This PR bumps `content-validator` version to:
* Perform case-insensitive checks while comparing pointers for entity metadata validation
* Perform proper items size validation upon deployments to have up-to 1MB thumbnails and 3MB in total

fix: deployments validation; performing case insensitive pointers check and proper thumbnails size validation
