content/src/Environment.ts
content/src/service/ServiceFactory.ts
content/src/service/ServiceImpl.ts
content/src/service/caching/Cache.ts
content/src/service/caching/CacheManager.ts
content/src/service/caching/CacheManagerFactory.ts
content/src/service/pointers/PointerManager.ts
content/src/service/pointers/PointerManagerFactory.ts
content/test/unit/service/pointers/PointerManager.spec.ts

**Syncing**
We are now syncing every 2 minutes. It used to be evert 45 seconds
**Caching**
1. We are now caching more scene entities.
2. Caches sizes can be set via environment variables
3. We now have a centralised place (the `CacheManager`) that generates all caches

Changes to sync time and caching

---

comms/lighthouse/src/handlers.ts
comms/lighthouse/src/readyStateService.ts
comms/lighthouse/src/routes.ts
comms/lighthouse/src/server.ts

Lighthouse now checks that the content server has signaled a "ready" state before accepting connections.

feat: Reject users until ready

---

content/src/service/time/TimeSorting.ts
content/src/storage/repositories/DeploymentsRepository.ts
content/src/storage/repositories/LastDeployedPointersRepository.ts
content/src/storage/repositories/PointerHistoryRepository.ts
content/test/integration/service/same-timestamp-check.spec.ts

We made sure we consistently handle entities with the same timestamp

fix: how to handle entities with same timestamp

---

comms/peer/src/Peer.ts
comms/peer/src/peerjs-server-connector/peerjsserverconnection.ts
version.bzl

Allows clients to get the actual cause of disconnection when awaiting connection to be established to properly address the issue.

fix: report disconnection cause

---

comms/peer/test/Peer.integration.spec.ts

We have a test that sometimes timeouts. We will add more time to it, to see if we can avoid the flakyness

chore: add more time to flaky test

---

content/src/controller/Controller.ts
content/src/denylist/Denylist.ts
content/src/service/auth/Authenticator.ts
content/test/integration/denylist/Denylist.spec.ts

This PR fixes https://github.com/decentraland/catalyst/issues/190

feat: return 400 error code when not authorised endpoint /denylist/{type}/{id}

---

content/src/Environment.ts
content/src/Server.ts
content/src/service/synchronization/ClusterSynchronizationManagerFactory.ts
content/src/service/synchronization/SynchronizationManager.ts
content/test/integration/E2ETestEnvironment.ts
content/test/integration/controller/deployment-fields.spec.ts
content/test/integration/denylist/Denylist.spec.ts
content/test/integration/errors/FailedDeploymentManager.spec.ts
content/test/integration/legacy-entities.spec.ts
content/test/integration/service/concurrent-deployments.spec.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/integration/service/deployments/pointer-changes-check.spec.ts
content/test/integration/service/garbage-collection/garbage-collection.spec.ts
content/test/integration/service/order-check.spec.ts
content/test/integration/service/same-timestamp-check.spec.ts
content/test/integration/service/snapshots/SnapshotManager.spec.ts
content/test/integration/upload-and-download.spec.ts

This PR fixes https://github.com/decentraland/catalyst/issues/192

feat: added a flag to disable synchronization

---

comms/lighthouse/src/configService.ts

Pretty much what the title says

chore: change max per layer default

---

docs/content-server-api/CONTENT_SERVER_API.md
docs/content-server-api/deployments/get.md
docs/content-server-api/history/get.md

Created a MD file to store all the endpoints related to Content Server API.
The documentation is work in progress, only two endpoints are documented.
The template for the documentation is from: https://github.com/jamescooke/restapidocs

Add documentation for content server API

---

.vscode/settings.json
content/src/BUILD.bazel
content/src/service/access/AccessCheckerForWearables.ts
content/src/service/access/AccessCheckerImpl.ts
content/test/integration/service/access/AccessCheckerImpl.spec.ts
content/test/unit/service/access/AccessCheckerImpl.spec.ts
package.json
yarn.lock

We are updating the content server access check by using the new wearable pointer format (urn)

fix: update wearable access check with new pointer format

---

content/src/Environment.ts
lambdas/src/Environment.ts

Update the-graph urls based on https://github.com/decentraland/collections-graph#decentraland-collections-graph

chore: update thegraph urls

---

lambdas/src/apis/profiles/controllers/profiles.ts
lambdas/test/apis/profiles/controller/profiles.spec.ts

We were translating worn wearables to urns, but forgot about the body shape.

fix: translate body shape to urn

---

comms/lighthouse/src/routes.ts

`this.app` was never set, so we are now passing it as a parameter

fix: app is undefined on lighthouse 

---

content/src/Environment.ts
content/src/controller/ControllerFactory.ts

We are now adding a way for catalyst owners to disable the denylist via config

feat: disable the denylist via config

---

content/src/Environment.ts
content/test/integration/denylist/Denylist.spec.ts
content/test/integration/syncronization/denylist-handling.spec.ts
content/test/integration/syncronization/error-handling.spec.ts

We are now disabling the denylist by default

BREAKING CHANGE: disable denylist by default

---

package.json
yarn.lock

Update to use https://github.com/decentraland/catalyst-client/pull/75 on the catalyst

perf: use local timestamp instead of offset when possible

---

content/src/service/synchronization/EventDeployer.ts

We are now specifying the catalyst where we learnt a deployment from if we fail to fetch some file during the internal deployment process

fix: include source with fetch problems

---

content/src/ContentMetrics.ts
content/src/repository/RepositoryQueue.ts
content/src/repository/extensions/DeploymentsRepository.ts
content/src/service/ServiceImpl.ts
content/test/helpers/repository/MockedRepository.ts
content/test/unit/service/Service.spec.ts

We are now exposing the total amount of deployments in the content server as a metric

chore: add deployments metric

---

content/src/migrations/scripts/1620152961576_add_deleter_indexes.ts

Feat: Add index for deleter deployment

---

content/src/Server.ts
content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/migrations/scripts/1620070748842_remove_origin.ts
content/src/migrations/scripts/1620221157277_add_lowercase_deployer_index.ts
content/src/repository/extensions/DeploymentsRepository.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/deployments/DeploymentManager.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/integration/controller/active-entity-by-content-hash.spec.ts
content/test/unit/repository/DeploymentsRepository.spec.ts
content/test/unit/repository/MockedDataBase.ts
docs/content-server-api/CONTENT_SERVER_API.md
docs/content-server-api/contents/hashId/active-entities/get.md
docs/content-server-api/contents/hashId/active-entity/get.md
docs/content-server-api/deployments/get.md
docs/content-server-api/history/get.md

This PR adds a new endpoint to search for a deployment having only the content hash.

Feat: Add endpoint to search content hash

---

content/src/service/access/AccessCheckerForWearables.ts

We are now adding an extra check when deploying wearables

fix: add extra checks when deploying wearables

---

comms/lighthouse/BUILD.bazel
comms/lighthouse/src/archipelagoService.ts
comms/lighthouse/src/configService.ts
comms/lighthouse/src/server.ts
package.json
yarn.lock

We are simply adding the archipelago library to the lighthouse. We are also updating the position with each heartbeat
Closes https://github.com/decentraland/catalyst/issues/500

feat: add archipelago library to lighthouse

---

comms/lighthouse/src/auth.ts
comms/lighthouse/src/server.ts
comms/peer/peer.package.json

chore: Extract authentication logic to other file

---

comms/lighthouse/src/peers/archipelagoService.ts
comms/lighthouse/src/server.ts
package.json
yarn.lock

We are doing two things in this PR:
1. We updated the `@dcl/archipelago` library
2. We now listen to events in the configService and send those updates to the archipelago controller

feat: send config updates to archipelago controller

---

lambdas/src/apis/collections/controllers/collections.ts
lambdas/src/apis/collections/types.ts

Add traits attributes to be used in third-party sites like [OpenSea](https://docs.opensea.io/docs/metadata-standards#section-attributes)

feat: add traits

---

comms/lighthouse/src/peerjs-server/models/realm.ts
comms/lighthouse/src/peers/peersService.ts
comms/lighthouse/src/routes.ts
comms/lighthouse/src/server.ts

Also, added an async handler for async routes (otherwise, errors would be ignored)

feat: Exposing current clients count

---

content/src/service/access/AccessCheckerForWearables.ts

When determining if a wearable should be deployed or not, we check if the deployer has access at the moment of the deployment, or if they had access 5 min before that.
Now, when we tried to find the block for the moment of the deployment, we would fail if we couldn't find it. This usually happened when the timestamp was so recent the that subgraph hadn't indexed the block yet. The thing is that we could have still performed the check for 5 min before that, since the block probably existed at that time. 
That's what we are doing now. Even if we can't find a block for the timestamp of the deployment, we still check for 5 min before that.

fix: avoid failing unnecessarily on wearables check

---

content/test/integration/E2EAssertions.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/TestServer.ts
content/test/integration/legacy-entities.spec.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/integration/upload-and-download.spec.ts
package.json
yarn.lock

Update catalyst client to include https://github.com/decentraland/catalyst-client/pull/96

chore: update catalyst client

---

content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/service/EntityFactory.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/ServiceStorage.ts
content/src/service/synchronization/EventDeployer.ts
content/src/service/synchronization/clients/ContentServerClient.ts
content/src/service/validations/Validations.ts
content/src/storage/ContentStorage.ts
content/src/storage/FileSystemContentStorage.ts
content/src/storage/S3ContentStorage.ts
content/test/helpers/service/EntityTestFactory.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/unit/denylist/DenylistServiceDecorator.spec.ts
content/test/unit/service/EntityFactory.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/service/validations/Validations.spec.ts
content/test/unit/storage/ContentStorage.spec.ts
content/test/unit/storage/FileSystemContentStorage.spec.ts
content/test/unit/storage/MockedStorage.ts
content/test/unit/storage/S3ContentStorage.spec.ts
package.json
yarn.lock

We update dcl-catalyst-commons to 5.0.0, and got rid of the `ContentFile` everywhere

Update commons lib

---

content/src/repository/extensions/PointerHistoryRepository.ts

After the investigation of https://github.com/decentraland/catalyst/issues/576 we found that increasing the limit to 10 is a workaround for this query to don't hang.

fix: Change limit to 10

---

comms/lighthouse/src/config/configService.ts
comms/lighthouse/src/peers/initPeerJsServer.ts
comms/lighthouse/src/routes.ts

Forwarded it to peerjs and exposed it in status

feat: Added config parameter for max users

---

comms/lighthouse/src/peers/archipelagoService.ts
comms/lighthouse/src/routes.ts

chore: Added islands count to status

---

comms/lighthouse/package.json
comms/lighthouse/src/server.ts
content/.gitignore
content/package.json
content/src/Environment.ts
content/src/Server.ts
content/src/controller/Controller.ts
content/test/integration/E2ETestEnvironment.ts
lambdas/package.json
lambdas/src/Environment.ts
lambdas/src/Server.ts
yarn.lock

feat: add openapi express middleware to validate requests

---

content/package.json
content/src/service/ServiceImpl.ts
content/src/service/validations/Validations.ts
content/src/service/validations/validations/ValidationsV4.ts
content/test/unit/service/validations/Validations.spec.ts
yarn.lock

Add metadata schema validation for v4 entities deployment.
Resolves #527.

feat: add metadata schema validation for v4 entities deployment

---

comms/lighthouse/src/server.ts
content/src/Environment.ts
lambdas/src/Environment.ts

Turn the default value of VALIDATE_API into false.

Set validate api as default false

---

lambdas/src/apis/profiles/controllers/profiles.ts
lambdas/src/apis/profiles/routes.ts
lambdas/test/apis/profiles/controller/profiles.spec.ts

feat: Profiles lambdas cache header

---

commons/servers/handlers.ts
comms/lighthouse/src/config/configService.ts
comms/lighthouse/src/routes.ts
comms/lighthouse/src/server.ts
comms/lighthouse/src/types.ts

For now, it only responds ice servers to use in kernel

feat: Added endpoint to fetch config parameters for comms

---

lambdas/src/apis/collections/controllers/wearables.ts
lambdas/src/utils/TheGraphClient.ts

fix: throw error when the graph queries fail

---

content/package.json
content/src/ports/postgres.ts
content/src/types.ts
yarn.lock

This PR adds node postgres implementation

Add node postgres class

---

content/.gitignore
content/src/controller/Controller.ts
content/src/migrations/scripts/1638045153758_add_audit_info_to_failed_deployments.ts
content/src/repository/extensions/DeploymentPointerChangesRepository.ts
content/src/repository/extensions/FailedDeploymentsRepository.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/deployments/DeploymentManager.ts
content/src/service/errors/FailedDeploymentsManager.ts
content/src/service/synchronization/EventDeployer.ts
content/test/integration/Server.spec.ts
content/test/integration/TestServer.ts
content/test/integration/errors/FailedDeploymentManager.spec.ts
content/test/unit/service/errors/NoOpFailedDeploymentsManager.ts

Add auth-chain to failed deployments and pointer-changes endpoint that will be used with new Synchronization.

feat: add authChain to failed deployments and pointer-changes endpoint

---

docs/CODEOWNERS
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/pull_request_template.md

Adds a code of conduct, codeowners, contribution guide, and pull request template

Chore: Added Contribution guidelines

---

README.md

Update the readme to have the contribution guides 

update readme to have the latest code of conduct and contribution guide

---

content/package.json
yarn.lock

Fixes weird condition in which files may not be closed before renaming

chore: update snapshot fetcher

---

content/README.md

Add missing `DISABLE_SYNCHRONIZATION` env in content docs, useful for development

docs: add `DISABLE_SYNCHRONIZATION` docs

---

.circleci/config.yml
content/jest.config.js
content/jest.globalSetup.ts
content/jest.globalTeardown.ts
content/package.json
content/test/integration/E2ETestEnvironment.ts
content/test/unit/service/Service.spec.ts
package.json
yarn.lock

Adds parallelism to `build-content` job, splitting test by timings. It also stores the result which give us some insights around the tests.
Adds a job for coverage collection and report.

test: trying circleci parallelism with jest

---

.circleci/config.yml
content/src/components.ts
content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/repository/Repository.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/garbage-collection/GarbageCollectionManager.ts
content/src/service/snapshots/SnapshotManager.ts
content/src/service/validations/validator.ts
content/src/storage/ContentStorage.ts
content/src/storage/ContentStorageFactory.ts
content/src/storage/FileSystemContentStorage.ts
content/src/storage/S3ContentStorage.ts
content/src/storage/compression.ts
content/test/helpers/service/MockedMetaverseContentService.ts
content/test/integration/Server.spec.ts
content/test/integration/service/snapshots/SnapshotManager.spec.ts
content/test/unit/service/Service.spec.ts
content/test/unit/storage/ContentStorage.spec.ts
content/test/unit/storage/ContentStorageWithStreams.spec.ts
content/test/unit/storage/FileSystemContentStorage.spec.ts
content/test/unit/storage/FileSystemUtils.ts
content/test/unit/storage/MockedStorage.ts
content/test/unit/storage/S3ContentStorage.spec.ts

Normalizes the storage implementation to remove friction on compressed assets

chore: normalize storage

---

content/package.json
content/src/components.ts
content/src/service/validations/validator.ts
yarn.lock

Adding logs to content-validator

chore: bump `content-validator` version

---

.vscode/settings.json
content/jest.config.js
content/package.json
content/src/controller/Controller.ts
content/src/denylist/DenylistServiceDecorator.ts
content/src/logic/deployments.ts
content/src/repository/RepositoryQueue.ts
content/src/service/Service.ts
content/src/service/ServiceImpl.ts
content/src/service/deployments/types.ts
content/src/service/synchronization/deployRemoteEntity.ts
content/src/service/validations/server.ts
content/src/storage/ContentStorage.ts
content/test/helpers/PromiseAssertions.ts
content/test/helpers/service/synchronization/MockedSynchronizationManager.ts
content/test/integration/E2ETestUtils.ts
content/test/integration/legacy-entities.spec.ts
content/test/integration/service/concurrent-deployments.spec.ts
content/test/integration/service/deployments/deployment-filters.spec.ts
content/test/integration/syncronization/node-onboarding.spec.ts
content/test/integration/upload-and-download.spec.ts
content/test/tsconfig.json
content/test/unit/denylist/DenylistServiceDecorator.spec.ts
content/test/unit/storage/RepositoryQueue.spec.ts
content/tsconfig.json
lambdas/package.json
yarn.lock

- Adds dozens of logs and validations.
- Makes the deployments _not fail_ when repeated:

add catch to deploy entity

---

content/src/Environment.ts
content/src/components.ts
content/src/logic/deployments.ts
content/src/service/synchronization/SynchronizationManager.ts
content/src/service/synchronization/retryFailedDeployments.ts
content/src/types.ts
content/test/helpers/service/synchronization/MockedSynchronizationManager.ts
content/test/integration/E2ETestEnvironment.ts
content/test/integration/syncronization/failed-deployments.spec.ts

Converts retry failed deployments job into a stoppable component.
Fixes condition to match with the ignore the fix error message.

fix: failed deployments report

---

package.json
yarn.lock

Remove unused `karma` dev dependency

chore: remove `karma` dev dependency

---

content/src/logic/cluster-helpers.ts

fix: issue #950

---

content/src/Environment.ts

Prevent logging sensitive environment variables like the credentials for Postgres
- Add an if to check that an env var is not on the list

chore: prevent logging sensitive environment variables

---

content/printApiCoverage.js

- Fail tests in the CI when there are untested endpoints
Closes https://github.com/decentraland/catalyst/issues/964
- Throw error if some endpoint was not tested on the CI

test: fail tests in the CI when there are untested endpoints

---

content/src/Environment.ts
content/src/components.ts
content/src/logic/config-helpers.ts
content/src/service/synchronization/batchDeployer.ts
docs/CONFIGURATION.md

Selectively ignore entity types on sync using environment variable

feat: ignore entity types

---

content/test/unit/logic/deployments.spec.ts
lambdas/src/utils/TheGraphClient.ts
lambdas/src/utils/third-party.ts
lambdas/test/apis/collections/controller/wearables/wearables-by-owner.spec.ts

Bug fixing:
- Showing only approved third party collections
- Filtering from TP ownership only matching collections

fix: TPW integration

---

content/src/Environment.ts

As the generation of bloom filter is failing with a timeout

Increase query time out

---

content/src/controller/Controller.ts
content/src/metrics.ts
content/src/service/ServiceImpl.ts
content/src/service/synchronization/deployRemoteEntity.ts

Adding a tag for deployment context to the metrics to trigger alerts when no synced deployments are done

fix: Add tag for deployments metric

---

content/src/controller/Controller.ts
content/src/logic/database-queries/deployments-queries.ts
content/test/integration/service/order-check.spec.ts
content/test/integration/service/same-timestamp-check.spec.ts

fixes https://github.com/decentraland/catalyst/issues/934

fix: remove overwritten by filter

---

lambdas/src/utils/third-party.ts
lambdas/test/utils/third-party.spec.ts

- Remove log4j lib to log as it wasn't working
- Fix the generation of TPW url

fix: tpw url and remove log4j logger

---

content/package.json
content/src/Environment.ts
content/src/components.ts
content/src/service/validations/validator.ts
yarn.lock

Bump content-validator to new version that includes new profile validations according to [ADR-75](https://github.com/decentraland/adr/blob/main/docs/ADR-75-profile-validations.md).

chore: bump content-validator

---

content/package.json
content/test/integration/controller/active-pointers.spec.ts
content/test/integration/resources/profile_original.json
content/test/integration/resources/profile_overwrite.json
content/test/integration/resources/scene_original.json
content/test/integration/resources/scene_overwrite.json

Add tests to unsure `active_pointers` table behavior 
Closes #1111

test: add integration tests for createEntity endpoint

---

lambdas/src/Server.ts

Remove unused params. Main reaseon for this is to test circleCI

refactor: remove unused params

---

content/src/instrument.ts
content/src/logic/database-queries/deployments-queries.ts
content/src/logic/database-queries/snapshots-queries.ts
content/src/ports/postgres.ts
content/test/unit/instrument.spec.ts

This PR adds optional instrumentation for stream queries.

feat: instrument stream queries

---

content/src/controller/Controller.ts

Fixes the 60secs timeout of a malformed request manually handling exceptions

fix: the 60secs timeout of a malformed request

---

content/package.json
content/src/logic/database-queries/deployments-queries.ts
content/src/metrics.ts
content/src/ports/activeEntities.ts
content/src/ports/postgres.ts
content/src/service/deployments/deployments.ts
content/test/unit/ports/postgres.spec.ts
content/test/unit/service/Service.spec.ts

* Separate optimized query for `/entities/active`.
* Better handling of transactional code.
* More metrics about db connection management.

fix: database handling

---

lambdas/src/apis/collections/controllers/collections.ts

Support for emotes in `/lambdas/collections/standard/erc721/{chainId}/{contract}/{option}/{emission}` endpoint

fix: /collections/erc 721 for emotes

---

content/package.json
content/src/components.ts
content/src/logic/snapshots.ts
content/src/ports/processedSnapshotStorage.ts
content/src/service/synchronization/batchDeployer.ts
content/src/service/synchronization/bootstrapFromSnapshots.ts
content/src/types.ts
content/test/integration/ports/processedSnapshotStorage.spec.ts
content/test/integration/syncronization/bootstrapping.spec.ts
content/test/unit/logic/snapshots.spec.ts
content/test/unit/ports/processedSnapshotStorage.spec.ts
yarn.lock

feat: fast bootstrapping fix background deploys

---

.circleci/config.yml

Replaces docker credentials for quay credentials

chore: replace docker for quay creds

---

content/package.json
lambdas/package.json
lambdas/src/MetricsServer.ts
lambdas/src/metrics.ts
yarn.lock

fix: Revert metrics changes

---

lambdas/src/apis/explore/controllers/explore.ts

Fixes: https://github.com/decentraland/catalyst/issues/1358

fix: lambdas with comms v3

---

content/src/logic/snapshots.ts
content/src/metrics.ts
content/src/service/synchronization/batchDeployer.ts

feat: fast bootstrapping fix mark as deployed

---

content/package.json
content/src/logic/database-queries/snapshots-queries.ts
content/src/service/snapshots/SnapshotManager.ts
content/test/integration/service/snapshots/SnapshotManager.spec.ts
yarn.lock

feat: fast bootstrapping concurrent

---

content/src/ports/activeEntities.ts
content/test/unit/service/Service.spec.ts

It reverts the fix applied on `e9995c714f0d401241897182d1db5fe28d7dd4f3` and `21e828ead0b621a94c35d5f8f12bb959ed666273` since it failed on peers.
No behavior changes are expected.

revert: pointers and ids retrieval from content by normalizing cases

---

content/package.json
content/src/service/synchronization/batchDeployer.ts
package.json
yarn.lock

fix: memory leak while syncing from scratch

---

content/package.json
content/test/integration/ports/deployer/metadata-schema-validations.spec.ts
yarn.lock

This PR only bumps @dcl/content-validator (which bumps @dcl/schemas) to base wearables deployment are allowed again.

fix: allow base wearables deployment

---

content/src/Environment.ts
content/src/components.ts

if both are provided, then on-chain validations are used

chore: accept l1 and l2 http providers

---

content/src/components.ts
content/src/controller/Controller.ts
content/src/logic/entities.ts
content/src/logic/erc721.ts
content/src/service/Server.ts
content/test/integration/controller/content.spec.ts
content/test/integration/controller/entity-metadata.spec.ts

feat: add getEntityImage, getEntityThumbnail and getERC721Entity endpoints

---

lambdas/src/utils/SmartContentClient.ts

Fix `client` resolution on `SmartContentClient`, it was returning a promise before.

fix: lambdas client resolver

---

lambdas/src/utils/SmartContentClient.ts

Fixes Server Content URL resolution on SmartContentClient.

fix: server content url resolution on SmartContentClient

---

content/src/Environment.ts
content/src/components.ts
content/src/service/auth/Authenticator.ts
content/test/unit/ports/activeEntities.spec.ts
content/test/unit/ports/deployer.spec.ts
yarn.lock

This PR introduces a new Decentraland Address, which will exclusively serve as the owner of deployments (of assets managed by DCL) in the `zone` environment.

feat: add new DCL address restricted to Zone deployments

---

content/package.json
yarn.lock

This PR upgrades the `@dcl/catalyst-contracts` package.
- Upgrades the package `@dcl/catalyst-contracts` version to `4.4.1`
- Breaking change (fix or feature that would cause existing functionality to change). If there's an API change, link the pull request in the [API spec repository](https://github.com/decentraland/catalyst-api-specs) and the accepted [DAO governance poll](https://governance.decentraland.org/)
- I have read the [**CONTRIBUTING**](https://github.com/decentraland/catalyst/blob/main/docs/CONTRIBUTING.md) document. …

fix: Upgrade @dcl/catalyst-contracts

---

content/src/Environment.ts

This PR set `on-chain` validations as default

feat: set on-chain validations as default

---

content/src/controller/handlers/get-content-handler.ts
content/test/integration/controller/entity-metadata.spec.ts

fix: opt-in for calculated Content-Type
